name: Pull Request Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled]

permissions:
  statuses: write

jobs:
  is-ready:
    runs-on: ubuntu-latest
    name: Label Check
    steps:
      - name: check-success
        id: check_success
        if: contains(github.event.pull_request.labels.*.name, 'マージOK')
        run: |
            curl --request POST \
            --url https://api.github.com/repos/${{github.repository}}/statuses/${{github.event.pull_request.head.sha}} \
            --header "authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            --header "content-type: application/json" \
            --data "{
            "context": "Label Check",
            "state": "success",
            "description": "マージできます"
            }"
      - name: check-pending
        if: steps.check_success.conclusion == 'skipped'
        run: |
            curl --request POST \
            --url https://api.github.com/repos/${{github.repository}}/statuses/${{github.event.pull_request.head.sha}} \
            --header "authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            --header "content-type: application/json" \
            --data "{
            "context": "Label Check",
            "state": "pending",
            "description": "\"マージOK\" ラベルを付けるとマージできます"
            }"
