name: Do Not Merge

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]

jobs:
  do-not-merge:
    runs-on: ubuntu-latest
    steps:
      - name: check labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "bug,enhancement,feature,question,documentation,help wanted,good first issue,invalid,wontfix"
          add_comment: true
          message: "This PR is being prevented from merging because the label is missing."